parameters:
    file.custome.files.class: FileBundle\Services\Files
    file.controller.file.class: FileBundle\Controller\FileController

services:

    file.files:
        class: "%file.custome.files.class%"
        arguments: ["@ceph.manager", "@security.token_storage", "@buzz" , "@router", "@fos_user.user_manager", "@doctrine.orm.default_entity_manager", "@mailer", "@twig", "%api_core.host%"]

    file.twig_extension:
        class: FileBundle\Twig\Extension\ByteFilter
        public: false
        tags:
            - { name: twig.extension }

    secondtodate.twig_extension:
        class: FileBundle\Twig\Extension\SecondToDateFilter
        public: false
        tags:
            - { name: twig.extension }
