parameters:
    file.files.class: FileBundle\Services\Files
    file.controller.file.class: FileBundle\Controller\FilesController

services:
    file.files:
        class: "%file.files.class%"
        arguments: ["@ceph.manager"]
    file.controller.file:
        class: "%file.controller.file.class%"
        arguments: ["@file.files"]
