imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FileBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@CephBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    oauth.facebook.id: 1733506483528117
    oauth.facebook.secret: a16da078a64f9391e921474823b04483
    oauth.google.id: 512528824517-1vav434osjl15n0e6ioi4sfijh20svhi.apps.googleusercontent.com
    oauth.google.secret: VzKZ2jBmsFKs4b7bxHFop7Ro
    oauth.twitter.id: 4X9f1Dj78DcqVvM6NL08GrW6m
    oauth.twitter.secret: mt1PA0F5td0pKOFvnt6ufJ9FvYaZbCT28yvTnDJSfpBck3gBAT

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session: ~
        # handler_id set to null will use default session handler from php.ini
#        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'AppBundle' ]

    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css'
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css'
            filters: [cssrewrite]

        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"

        jquery:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.js'
sensio_buzz:
    client_timeout: -1

hwi_oauth:
    connect:
        account_connector: app.user_provider
    firewall_name: main
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%oauth.facebook.id%"
            client_secret:       "%oauth.facebook.secret%"
            scope:               "email"
            options:
                display: popup #dialog is optimized for popup window
        google:
            type:                google
            client_id:           "%oauth.google.id%"
            client_secret:       "%oauth.google.secret%"
            scope:               "email profile"
        twitter:
            type:                twitter
            client_id:           "%oauth.twitter.id%"
            client_secret:       "%oauth.twitter.secret%"
            options:
                include_email: true