hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

twitter_login:
    path: /login/check-twitter

fos_user_security_login:
    path: /login
    defaults: { _controller: "AppBundle:Security:login" }
    methods:  [GET, POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

file:
    resource: "@FileBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /