file:
    resource: "@FileBundle/Resources/config/routing.yml"
    prefix:   /files

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"