hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    path: /login/check-facebook

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

file:
    resource: "@FileBundle/Resources/config/routing.yml"
    prefix:   /files

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /