app_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app_paypal_paiement:
    path: /paiement
    defaults: { _controller: AppBundle:Paypal:index }

app_paypal_purchase:
    path: /paiement/purchase
    defaults: { _controller: AppBundle:Paypal:payment }

app_paypal_canceled:
    path: /paiement/canceled
    defaults: { _controller: AppBundle:Paypal:canceledPayment }

app_paypal_completed:
    path: /paiement/completed
    defaults: { _controller: AppBundle:Paypal:completedPayment }