parameters:
    app.user_provider.class: AppBundle\Services\UserProvider
    app.registration_success.class: AppBundle\Services\RegistrationSuccess
    app.acl.class: AppBundle\Services\Acl

services:
    app.user_provider:
        class: "%app.user_provider.class%"
        arguments: ["@fos_user.user_manager", {'facebook': "%oauth.facebook.id%"}]
    app.acl:
        class: "%app.acl.class%"
        arguments: ["@security.acl.provider", "@security.token_storage"]
    app.registration_success:
        class: "%app.registration_success.class%"
        arguments: ["@ceph.manager"]
        tags:
            - { name: kernel.event_subscriber }